name: Build

on: push

jobs:
  build:
    name: Phar building
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[Build]')"

    steps:
      - name: Startup
        uses: actions/checkout@v3
      - name: Download PHP Release
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          file: PHP-Linux-x86_64-PM5.tar.gz
          repo: NetherGamesMC/php-build-scripts
          version: "tags/php-8.3-latest"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Unpack PHP Release
        run: tar -xzvf PHP-Linux-x86_64-PM5.tar.gz
      - name: Download pharbuilder-rs
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          file: pharbuilder
          repo: NetherGamesMC/pharbuilder-rs
          token: ${{ secrets.ng_token }}
      - name: Build
        run: |
          echo Building...
          chmod +x pharbuilder
          ./pharbuilder -i . -o ./BlockLagFix.phar
          echo Build completed!
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: BlockLagFix
          path: BlockLagFix.phar
